---
title: "analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(DBI)
library(RSQLite)
library(dplyr)
library(tidyr)
library(gt)

con <- dbConnect(SQLite(), "inst/extdata/jazz.sqlite")
```

## 1. Study Design & Demographics

In this example, I need to get the general information from study_table

```{r}
study_description <-dbGetQuery(con, "SELECT study_id, study_design FROM study_table;")
```

And some manipulations from trial_subject_table, and lookup from drug_table

```{r}
drug_counts <- dbGetQuery(con, "SELECT 
                                  distinct study_id, drug_id,
                                  count(*) d_count
                                FROM trial_subject_table 
                                WHERE study_id = '14-002'
                                GROUP BY drug_id;")

drug_names <- dbGetQuery(con, "SELECT 
                                 distinct drug_id, drug_name
                               FROM drug_table;")

# I COULD push these to SQL, but it becomes unreadable. Let's do it if necessary.

study_subjects <- drug_counts %>% 
  inner_join(drug_names, "drug_id") %>% 
  select(study_id, drug_name, d_count)

study_subject_tbl <- study_subjects %>% 
  unite("drug_name", c(drug_name, d_count), sep = " n=") %>% 
  group_by(study_id) %>% 
  summarize(drug_name = paste(drug_name, collapse = "<br>"), .groups = "drop")
```

Person age info

```{r}
mean_age <- dbGetQuery(con, "SELECT AVG(person_age) mean_age
                             FROM person_table
                             WHERE person_id IN (
                               SELECT distinct person_id
                               FROM trial_subject_table
                               WHERE study_id = '14-002'
                             );")

min_age <- dbGetQuery(con, "SELECT MIN(person_age) min_age
                            FROM person_table
                            WHERE person_id IN (
                              SELECT distinct person_id
                              FROM trial_subject_table
                              WHERE study_id = '14-002'
                            );")

max_age <- dbGetQuery(con, "SELECT MAX(person_age) max_age
                            FROM person_table
                            WHERE person_id IN (
                              SELECT distinct person_id
                              FROM trial_subject_table
                              WHERE study_id = '14-002'
                            );")

age_tbl <- tibble(
  study_id = "14-002",
  mean_age = paste0(round(mean_age, digits = 1), " years (", min_age, " to ", max_age, ")")
)
```

Person sex info

```{r}
sex_count <- dbGetQuery(con, "SELECT person_sex, count(*) as n
                              FROM person_table
                              WHERE person_id IN (
                                           SELECT distinct person_id
                                           FROM trial_subject_table
                                           WHERE study_id = '14-002'
                                         )
                              GROUP BY person_sex;")

sex_tbl <- sex_count %>% 
  mutate(n = paste0(round(n / sum(n), digits = 3) * 100, "%")) %>% 
  unite("sex", c(person_sex, n), sep = ": ") %>% 
  summarize(sex = paste(sex, collapse = "<br>")) %>% 
  mutate(study_id = "14-002")
```

```{r}
gt(
  study_description %>% 
    inner_join(study_subject_tbl, "study_id") %>% 
    inner_join(age_tbl, "study_id") %>% 
    inner_join(sex_tbl, "study_id") 
) %>% 
  fmt_markdown(columns = c("drug_name", "sex"))
```


